# Generated by Django 2.2 on 2019-09-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('entitys', models.TextField()),
                ('label', models.TextField(blank=True, null=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('is_Process', models.IntegerField()),
                ('article_id', models.ForeignKey(on_delete='CASCADE', to='articles.Article')),
            ],
        ),
    ]
