# Generated by Django 2.2 on 2019-09-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('is_yuqing', models.IntegerField()),
                ('source', models.CharField(max_length=200)),
                ('introduce', models.TextField()),
                ('content', models.TextField()),
                ('word', models.CharField(max_length=50)),
                ('content_sentence_parser', models.TextField(blank=True, null=True)),
                ('content_entity', models.TextField(blank=True, null=True)),
                ('content_svos', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
