# Generated by Django 2.2 on 2019-08-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='finish_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
